"""Local text embeddings via sentence-transformers.

Anthropic does not offer an embeddings endpoint, so retrieval uses a small
open model that runs locally (free, offline, no API calls). Answers are still
generated by Claude in `qa.py`.
"""

from __future__ import annotations

import os
from functools import lru_cache

import numpy as np

DEFAULT_MODEL = os.getenv("EMBEDDING_MODEL", "sentence-transformers/all-MiniLM-L6-v2")


@lru_cache(maxsize=2)
def _load_model(name: str):
    # Imported lazily so the app starts fast and only pays the import cost once.
    from sentence_transformers import SentenceTransformer

    return SentenceTransformer(name)


def embed(texts: list[str], model_name: str = DEFAULT_MODEL) -> np.ndarray:
    """Embed a list of texts into an L2-normalized float32 matrix (n, dim).

    Normalizing means a plain dot product equals cosine similarity, which keeps
    the vector store simple.
    """
    if not texts:
        return np.zeros((0, 384), dtype=np.float32)
    model = _load_model(model_name)
    vectors = model.encode(
        texts,
        normalize_embeddings=True,
        convert_to_numpy=True,
        show_progress_bar=False,
    )
    return vectors.astype(np.float32)


def embed_one(text: str, model_name: str = DEFAULT_MODEL) -> np.ndarray:
    """Embed a single string into a 1-D vector."""
    return embed([text], model_name)[0]
